# config/enhanced_config.yaml
translation_systems:
  indictrans2:
    models:
      en_indic: "ai4bharat/indictrans2-en-indic-dist-200M"  # Using 200M distilled for speed
      indic_en: "ai4bharat/indictrans2-indic-en-dist-200M"  # Using 200M distilled for speed
    languages:
      - code: eng_Latn
        name: English
        script: Latin
      - code: hin_Deva
        name: Hindi
        script: Devanagari
      - code: urd_Arab
        name: Urdu
        script: Arabic
    
  opus_mt:
    models:
      en_zh: "Helsinki-NLP/opus-mt-en-zh"
      zh_en: "Helsinki-NLP/opus-mt-zh-en"
    languages:
      - code: en
        name: English
        script: Latin
      - code: zh
        name: Chinese (Simplified)
        script: Chinese

# Supported translation pairs
translation_pairs:
  direct:
    # IndicTrans2 pairs
    - src: eng_Latn
      tgt: hin_Deva
      system: indictrans2
    - src: hin_Deva
      tgt: eng_Latn
      system: indictrans2
    - src: eng_Latn
      tgt: urd_Arab
      system: indictrans2
    - src: urd_Arab
      tgt: eng_Latn
      system: indictrans2
    
    # OPUS-MT pairs
    - src: en
      tgt: zh
      system: opus_mt
    - src: zh
      tgt: en
      system: opus_mt
    
    # Cross-system compatibility
    - src: eng_Latn
      tgt: zh
      system: opus_mt
      note: "English (IndicTrans format) to Chinese"
    - src: zh
      tgt: eng_Latn
      system: opus_mt
      note: "Chinese to English (IndicTrans format)"
  
  multi_step:
    # Examples of supported multi-step translations
    - src: hin_Deva
      tgt: zh
      via: eng_Latn
      note: "Hindi → English → Chinese"
    - src: zh
      tgt: hin_Deva
      via: eng_Latn
      note: "Chinese → English → Hindi"
    - src: urd_Arab
      tgt: zh
      via: eng_Latn
      note: "Urdu → English → Chinese"
    - src: zh
      tgt: urd_Arab
      via: eng_Latn
      note: "Chinese → English → Urdu"

# Performance settings
performance:
  model_caching: true
  device_priority: ["cuda", "mps", "cpu"]
  batch_size: 1
  max_length: 512
  beam_search:
    num_beams: 4
    length_penalty: 0.8
    early_stopping: true

# Quality settings
quality:
  indictrans2:
    bleu_score_range: "35-45"
    note: "High quality for Indian languages"
  opus_mt:
    bleu_score_range: "31-36"
    note: "Good quality for Chinese translations"

# File support
file_formats:
  supported: [".txt", ".json", ".csv"]
  encoding: "utf-8"
  preservation:
    txt: "line_breaks"
    json: "structure"
    csv: "columns"